<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    carpetbeggers
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
  public function save(Doctrine_Connection $conn = null)
  {
    if (is_numeric(substr($this->get('name'), 0, 1)))
    {
      $this->setSort('size');
    }
    else 
    {
      $this->setSort('type');
    }
    
    parent::save($conn);
  }
}
