all:
  javascripts: [jq/jcarousel, http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js]
  stylesheets: [gallery, http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/base/jquery-ui.css]