prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_PARSE | E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    csrf_secret:            7c6a29010c2f5b70b7f62fb742a3c7d9509ec1c3

    enabled_modules:        [default, sfGuardAuth, seegnoModal, seegnoPages, seegnoPagesAdmin, seegnoI18N]
    standard_helpers:       [Partial, Cache, jQuery, I18N, seegno, seegnoI18N]

    i18n:                   on
    default_culture:        en

    jquery_core:            jquery-1.4.2.min.js

    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    use_database:           true

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

    file_link_format:       txmt://open?url=file://%f&line=%l

  .actions:
    error_404_module: core
    error_404_action: error404