<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $template
 * @property boolean $is_published
 * @property string $module
 * @property string $action
 * @property string $keywords
 * @property string $description
 * @property string $menu
 * @property string $link
 * @property Doctrine_Collection $Slots
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getTemplate()     Returns the current record's "template" value
 * @method boolean             getIsPublished()  Returns the current record's "is_published" value
 * @method string              getModule()       Returns the current record's "module" value
 * @method string              getAction()       Returns the current record's "action" value
 * @method string              getKeywords()     Returns the current record's "keywords" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method string              getMenu()         Returns the current record's "menu" value
 * @method string              getLink()         Returns the current record's "link" value
 * @method Doctrine_Collection getSlots()        Returns the current record's "Slots" collection
 * @method Page                setTitle()        Sets the current record's "title" value
 * @method Page                setTemplate()     Sets the current record's "template" value
 * @method Page                setIsPublished()  Sets the current record's "is_published" value
 * @method Page                setModule()       Sets the current record's "module" value
 * @method Page                setAction()       Sets the current record's "action" value
 * @method Page                setKeywords()     Sets the current record's "keywords" value
 * @method Page                setDescription()  Sets the current record's "description" value
 * @method Page                setMenu()         Sets the current record's "menu" value
 * @method Page                setLink()         Sets the current record's "link" value
 * @method Page                setSlots()        Sets the current record's "Slots" collection
 * 
 * @package    carpetbeggers
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('template', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('menu', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Slot as Slots', array(
             'local' => 'id',
             'foreign' => 'page_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => false,
             ));
        $auditable0 = new Doctrine_Template_Auditable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => false,
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'keywords',
              2 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($auditable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
    }
}